GET http://localhost:3000/post
Authorization: Bearer 

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Dozie",
    "password": "Dozzy2001..."
}

###

POST http://localhost:4000/signin
Content-Type: application/json

{
    "username": "Dozie",
    "password": "Dozzy2001..."
}


###

POST http://localhost:4000/token
Content-Type: application/json

{ 
    "token": 
}