GET http://localhost:3000/post
Authorization: Bearer


###



POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Dozie",
    "password": "Daddy2111"
}

###

POST http://localhost:4000/signin
Content-Type: application/json

{
    "username": "Dozie",
    "password": "Daddy2111"
}


###

POST http://localhost:4000/token
Content-Type: application/json

{ 
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRG96aWUiLCJpYXQiOjE3MDYzNzYzMTZ9.da4w1FdGNPwmH7HRY-mttUdJCyqqUGvOVKGD5hcnT04"
}